name: Build sing-box

on: 
  push:
  pull_request:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout sing-box
      uses: actions/checkout@v2
      with:
        repository: sagernet/sing-box
        fetch-depth: 0
        
    - name: Set up Go  
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc g++ make
    
    - name: Compile
      env:
        CGO_ENABLED: 1
        TAGS: "with_gvisor,with_quic,with_dhcp,with_wireguard,with_shadowsocksr,with_ech,with_utls,with_reality_server,with_acme,with_clash_api,with_v2ray_api"
      run: |
        go install -v -tags "$TAGS" ./cmd/sing-box

    - name: Rename binary 
      run: |
        mv ~/go/bin/sing-box ~/sing-box

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: sing-box
        path: ~/sing-box
